apiVersion: v1
kind: ServiceAccount
metadata:
  name: create-tokens
  namespace: gitops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: create-tokens
  namespace: gitops
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - create
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: create-tokens
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: create-tokens
subjects:
  - kind: ServiceAccount
    name: create-tokens
    namespace: gitops
