{{- range untilStep 1 (int ($.Values.users | add 1)) 1 }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  labels:
    argocd.argoproj.io/project-inherit: global
  name: team{{ . }}
  namespace: gitops
spec:
  description: user{{ . }} project
  destinations:
  - name: in-cluster
    namespace: user{{ . }}-argocd
  - name: in-cluster
    namespace: user{{ . }}-dev
  - name: in-cluster
    namespace: user{{ . }}-stage
  - name: in-cluster
    namespace: user{{ . }}-prod
  - name: in-cluster
    namespace: user{{ . }}-cicd
  roles:
  - description: Team{{ . }} admins
    groups:
    - team{{ . }}
    - user{{ . }}-cli
    name: admin
    policies:
    - p, proj:team{{ . }}:admin, applications, *, team{{ . }}/*, allow
    - p, proj:team{{ . }}:admin, exec, create, team{{ . }}/*, allow
  - description: Pipeline accounts
    groups:
    - user{{ . }}-pipeline
    name: pipeline
    policies:
    - p, proj:team{{ . }}:pipeline, applications, get, team{{ . }}/*, allow
    - p, proj:team{{ . }}:pipeline, applications, sync, team{{ . }}/*, allow
  sourceNamespaces:
  - user{{ . }}-argocd
  sourceRepos:
  - '*'
{{- end }}
