apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '25'
  labels:
    app-source: local.home
    repo: cluster-config
  name: rhtpa-infra
  namespace: openshift-gitops
spec:
  destination:
    namespace: trusted-profile-analyzer
    server: https://kubernetes.default.svc
  project: cluster-config
  sources:
  - repoURL: 'https://github.com/redhat-appstudio/rhtap-cli'
    path: charts/rhtap-infrastructure
    targetRevision: release-1.2
    helm:
      valueFiles:
      - $values/charts/prometheus/values.yaml
  - repoURL: 'https://github.com/AdvancedDevSecOpsWorkshop/bootstrap'
    path: infra/rhtpa/infra/base
    targetRevision: HEAD
    ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
