default:
  app:
    enabled: true
    enableAutoSync: true
    autoSyncPrune: false
    project: cluster-config
    labels:
      app-source: local.home
      repo: cluster-config
    destination:
      namespace: openshift-gitops
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/AdvancedDevSecOpsWorkshop/bootstrap
      targetRevision: HEAD

applications:

  rbac:
    annotations:
      argocd.argoproj.io/sync-wave: '0'
    destination:
      namespace: openshift-gitops
    source:
      path: infra/rbac/base

  cert-manager:
    annotations:
      argocd.argoproj.io/sync-wave: '0'
    destination:
      namespace: cert-manager
    source:
      path: infra/cert-manager-operator/aggregate/overlays/letsencrypt

  console-links:
    annotations:
      argocd.argoproj.io/sync-wave: '1'
    source:
      path: infra/consolelinks/base

  acs:
    annotations:
      argocd.argoproj.io/sync-wave: '11'
    destination:
      namespace: stackrox
    source:
      path: infra/acs-operator/overlays/oauth

  devspaces:
    annotations:
      argocd.argoproj.io/sync-wave: '11'
    destination:
      namespace: devspaces
    source:
      repoURL: https://github.com/redhat-cop/gitops-catalog
      path: devspaces/aggregate/overlays/default

  gitea:
    annotations:
      argocd.argoproj.io/sync-wave: '11'
    destination:
      namespace: gitea
    source:
      path: infra/gitea/base
    syncPolicyRetry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  keycloak-operator:
    annotations:
      argocd.argoproj.io/sync-wave: '11'
    destination:
      namespace: keycloak
    source:
      path: infra/keycloak-operator/operator/base

  pipelines:
    annotations:
      argocd.argoproj.io/sync-wave: '11'
    destination:
      namespace: openshift-pipelines
    source:
      path: infra/pipelines-operator/base

  keycloak-instance:
    annotations:
      argocd.argoproj.io/sync-wave: '21'
    destination:
      namespace: keycloak
    source:
      path: infra/keycloak-operator/instance/base

  keycloak-realm-import:
    annotations:
      argocd.argoproj.io/sync-wave: '31'
    destination:
      namespace: keycloak
    source:
      path: infra/keycloak-operator/realm-import
      extraSourceFields: |
        helm:
            values: |
              users: ${USERS}
              sub_domain: ${SUB_DOMAIN}

  openshift-oauth:
    annotations:
      argocd.argoproj.io/sync-wave: '41'
    destination:
      namespace: openshift-config
    source:
      path: infra/oauth/base

  # Quay won't start without keycloak being up and running
  # Also Quay tends to be the most problematic component so
  # this last
  quay:
    annotations:
      argocd.argoproj.io/sync-wave: '51'
    destination:
      namespace: quay-operator
    source:
      path: infra/quay-registry-operator/overlays/default
    extraFields: |
      ignoreDifferences:
      - group: ""
        kind: Secret
        jsonPointers:
        - /data/tls.crt
        - /data/tls.key
        name: config-bundle-secret
        namespace: quay-operator
