apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: central
  namespace: stackrox
spec:
  secretName: central-default-tls-cert
  renewBefore: 240h0m0s
  duration: 2160h0m0s
  dnsNames:
  - central-stackrox.${SUB_DOMAIN}
  issuerRef:
    name: zerossl-production-ec2
    kind: ClusterIssuer
