commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
  - certificate.yaml
  - github.com/redhat-cop/gitops-catalog/advanced-cluster-security-operator/operator/overlays/latest
  - github.com/redhat-cop/gitops-catalog/advanced-cluster-security-operator/instance/overlays/internal-registry-integration
  - acs-policy-init.yaml

patches:
  - patch: |-
      - op: replace
        path: /spec/channel
        value: 'rhacs-4.6'
    target:
      kind: Subscription
      name: rhacs-operator
  - patch: |-
      - op: replace
        path: /spec/perNode/collector/collection
        value: EBPF
    target:
      kind: SecuredCluster
  - patch: |-
      - op: add
        path: /spec/central/declarativeConfiguration
        value:
          configMaps:
            - name: declarative-configurations
    target:
      kind: Central
  - patch: |-
      - op: add
        path: /spec/scannerV4
        value:
          db:
            persistence:
              persistentVolumeClaim:
                claimName: scanner-v4-db
          indexer:
            scaling:
              autoScaling: Enabled
              maxReplicas: 5
              minReplicas: 2
              replicas: 3
          scannerComponent: Default
    target:
      kind: SecuredCluster
