apiVersion: batch/v1
kind: Job
metadata:
  name: configure-gitea
  namespace: gitea
  # annotations:
  #   argocd.argoproj.io/hook: PostSync
  #   argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
        - image: registry.redhat.io/ansible-automation-platform-21/ee-supported-rhel8:1.0
          env:
          - name: sub_domain
            value: ${SUB_DOMAIN}
          - name: branch
            value: main
          - name: password
            value: password
          - name: users
            value: " ${USERS} "
          command:
            - /bin/bash
            - -c
            - |
              #!/usr/bin/env bash

              echo "Setup temporary OCP user to make ansible happy"

              echo "tempuser:x:$(id -u):$(id -g):,,,:${HOME}:/bin/bash" >> /etc/passwd
              echo "tempuser:x:$(id -G | cut -d' ' -f 2)" >> /etc/group
              id

              git clone https://github.com/AdvancedDevSecOpsWorkshop/gitea
              cd gitea
              git checkout ${branch}
              cd infra/components/gitea/base/gitea-configure-playbook

              ansible-playbook main.yaml -e gitea_password=$password -e sub_domain=$sub_domain -e users=$users
          name: configure-gitea
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      serviceAccount: automation
      serviceAccountName: automation
