apiVersion: pfe.rhpds.com/v1
kind: Gitea
metadata:
  name: gitea
  namespace: gitea
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  giteaConfigMapName: gitea-custom-config
  giteaHostname: gitea-gitea.${SUB_DOMAIN}
  giteaSsl: true
  giteaAdminUser: gitea-admin
  giteaAdminPassword: "openshift"
  giteaAdminPasswordLength: 32
  giteaAdminEmail: gitea-admin@ignore-redhat.com
  giteaCreateUsers: true
  giteaUserNumber: ${USERS}
  giteaUserPassword: "openshift"
  giteaMigrateRepositories: true
  giteaRepositoriesList:
    - repo: https://github.com/AdvancedDevSecOpsWorkshop/workshop.git
      name: workshop
      private: true
    - repo: https://github.com/OpenShiftDemos/web-nodejs.git
      name: web-nodejs
      private: true
    - repo: https://github.com/AdvancedDevSecOpsWorkshop/gitops.git
      name: gitops
      private: true
