apiVersion: v1
kind: Secret
metadata:
  name: config-bundle-secret
  namespace: quay-operator
stringData:
  config.yaml: |
    SUPER_USERS:
    - admin
    - clusteradmin
    FEATURE_UI_V2: true
    FEATURE_REFERRERS_API: true
    BROWSER_API_CALLS_XHR_ONLY: false
    FEATURE_TEAM_SYNCING: true
    FEATURE_NONSUPERUSER_TEAM_SYNCING_SETUP: true
    AUTHENTICATION_TYPE: OIDC
    KEYCLOAK_LOGIN_CONFIG:
      CLIENT_ID: quay
      CLIENT_SECRET: 5d71fc1a-feb8-4a9c-8eb9-1f5605c174bf
      OIDC_SERVER: https://keycloak.${SUB_DOMAIN}/realms/openshift/
      SERVICE_NAME: Keycloak
      SERVICE_ICON: https://upload.wikimedia.org/wikipedia/commons/2/29/Keycloak_Logo.png
      VERIFIED_EMAIL_CLAIM_NAME: email
      PREFERRED_USERNAME_CLAIM_NAME: preferred_username
      PREFERRED_GROUP_CLAIM_NAME: groups
      LOGIN_SCOPES:
          - openid
