apiVersion: v1
kind: Secret
metadata:
  name: config-bundle-secret
  namespace: quay-operator
stringData:
  config.yaml: |
    FEATURE_USER_INITIALIZE: true
    BROWSER_API_CALLS_XHR_ONLY: false
    SUPER_USERS:
    - admin
    - clusteradmin
    FEATURE_USER_CREATION: true
    AUTHENTICATION_TYPE: OIDC
    FEATURE_TEAM_SYNCING: true
    FEATURE_NONSUPERUSER_TEAM_SYNCING_SETUP: true
    FEATURE_V2_UI: true
    KEYCLOAK_LOGIN_CONFIG:
      CLIENT_ID: quay
      CLIENT_SECRET: 5d71fc1a-feb8-4a9c-8eb9-1f5605c174bf
      OIDC_SERVER: https://keycloak.${SUB_DOMAIN}/realms/openshift/
      SERVICE_NAME: Keycloak
      VERIFIED_EMAIL_CLAIM_NAME: email
      PREFERRED_USERNAME_CLAIM_NAME: preferred_username
      PREFERRED_GROUP_CLAIM_NAME:: groups
      LOGIN_BINDING_FIELD: preferred_username
      LOGIN_SCOPES:
          - openid
