apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: quay-operator

resources:
- github.com/redhat-cop/gitops-catalog/quay-operator/operator/overlays/stable-3.11
- automation-sa.yaml
- config-bundle-secret.yaml
- registry.yaml
- init-user-password.yaml
- init-quay-job.yaml
- configure-quay-job.yaml
