apiVersion: noobaa.io/v1alpha1
kind: BackingStore
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  labels:
    app: noobaa
  name: noobaa-default-backing-store
  namespace: openshift-storage
spec:
  pvPool:
    numVolumes: 1
    resources:
      requests:
        storage: 500Gi
    storageClass: quay-gp3-csi
  type: pv-pool
