apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: ocs-storagecluster
  namespace: openshift-storage
spec:
  multiCloudGateway:
    dbStorageClassName: quay-gp3-csi
    reconcileStrategy: standalone
  resources:
    noobaa-core:
      limits:
        cpu: "3"
        memory: "6Gi"
      requests:
        cpu: "3"
        memory: "6Gi"
    noobaa-db:
      limits:
        cpu: "2"
        memory: "4Gi"
      requests:
        cpu: "2"
        memory: "4Gi"
    noobaa-endpoint:
      limits:
        cpu: "2"
        memory: 4Gi
      requests:
        cpu: "2"
        memory: 4Gi
